CREATE TABLE tb_arquivo (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id     BIGINT       NOT NULL,
    atendimento_id  BIGINT,
    tipo            VARCHAR(40)  NOT NULL,
    nome_original   VARCHAR(255) NOT NULL,
    mime_type       VARCHAR(100) NOT NULL,
    tamanho_bytes   BIGINT       NOT NULL,
    storage_key     VARCHAR(500) NOT NULL,
    descricao       VARCHAR(500),
    criado_por_id   BIGINT       NOT NULL,
    criado_em       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_arquivo_storage_key UNIQUE (storage_key),
    CONSTRAINT fk_arquivo_paciente FOREIGN KEY (paciente_id) REFERENCES tb_paciente (usuario_id),
    CONSTRAINT fk_arquivo_atendimento FOREIGN KEY (atendimento_id) REFERENCES tb_atendimento (id),
    CONSTRAINT fk_arquivo_criado_por FOREIGN KEY (criado_por_id) REFERENCES tb_usuario (id)
);

CREATE INDEX idx_arquivo_paciente ON tb_arquivo (paciente_id);
CREATE INDEX idx_arquivo_tipo ON tb_arquivo (paciente_id, tipo);
