-- Schema inicial do OdontoHelp (baseado nas entidades JPA).
-- Convenção: novas alterações de schema devem ser feitas em novos arquivos
-- db/migration/V{n}__descricao.sql (nunca editar migrations já aplicadas).

CREATE TABLE tb_usuario (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(100) NOT NULL,
    telefone        VARCHAR(15)  NOT NULL,
    email           VARCHAR(100),
    senha           VARCHAR(255),
    cpf             VARCHAR(11),
    perfil          VARCHAR(255) NOT NULL,
    is_ativo        BOOLEAN      NOT NULL,
    genero          VARCHAR(255),
    data_nascimento DATE,
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT uk_usuario_cpf   UNIQUE (cpf)
);

CREATE TABLE tb_endereco (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT,
    rua         VARCHAR(100) NOT NULL,
    numero      VARCHAR(10)  NOT NULL,
    complemento VARCHAR(50),
    bairro      VARCHAR(50)  NOT NULL,
    cidade      VARCHAR(50)  NOT NULL,
    uf          VARCHAR(2)   NOT NULL,
    cep         VARCHAR(8)   NOT NULL,
    CONSTRAINT uk_endereco_usuario UNIQUE (usuario_id),
    CONSTRAINT fk_endereco_usuario FOREIGN KEY (usuario_id) REFERENCES tb_usuario (id)
);

CREATE TABLE tb_paciente (
    usuario_id          BIGINT PRIMARY KEY,
    observacoes_medicas TEXT,
    CONSTRAINT fk_paciente_usuario FOREIGN KEY (usuario_id) REFERENCES tb_usuario (id)
);

CREATE TABLE tb_dentista (
    usuario_id BIGINT PRIMARY KEY,
    cro        VARCHAR(12) NOT NULL,
    CONSTRAINT uk_dentista_cro UNIQUE (cro),
    CONSTRAINT fk_dentista_usuario FOREIGN KEY (usuario_id) REFERENCES tb_usuario (id)
);

CREATE TABLE tb_procedimento (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome             VARCHAR(150)   NOT NULL,
    descricao        TEXT,
    valor_base       NUMERIC(10, 2) NOT NULL,
    duracao_minutos  INTEGER        NOT NULL,
    cor_legenda      VARCHAR(7),
    is_ativo         BOOLEAN        NOT NULL
);

CREATE TABLE tb_agendamento (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_inicio  TIMESTAMP    NOT NULL,
    data_fim     TIMESTAMP    NOT NULL,
    observacoes  TEXT,
    status       VARCHAR(255) NOT NULL,
    paciente_id  BIGINT       NOT NULL,
    dentista_id  BIGINT       NOT NULL,
    CONSTRAINT fk_agendamento_paciente FOREIGN KEY (paciente_id) REFERENCES tb_paciente (usuario_id),
    CONSTRAINT fk_agendamento_dentista FOREIGN KEY (dentista_id) REFERENCES tb_dentista (usuario_id)
);

CREATE TABLE tb_atendimento (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agendamento_id       BIGINT       NOT NULL,
    dentista_id          BIGINT       NOT NULL,
    paciente_id          BIGINT       NOT NULL,
    hora_inicio          TIMESTAMP    NOT NULL,
    hora_fim             TIMESTAMP,
    observacoes_gerais   TEXT,
    status               VARCHAR(255) NOT NULL,
    odontograma_revisado BOOLEAN      NOT NULL,
    criado_em            TIMESTAMP,
    atualizado_em        TIMESTAMP,
    CONSTRAINT uk_atendimento_agendamento UNIQUE (agendamento_id),
    CONSTRAINT fk_atendimento_agendamento FOREIGN KEY (agendamento_id) REFERENCES tb_agendamento (id),
    CONSTRAINT fk_atendimento_dentista    FOREIGN KEY (dentista_id)    REFERENCES tb_dentista (usuario_id),
    CONSTRAINT fk_atendimento_paciente    FOREIGN KEY (paciente_id)    REFERENCES tb_paciente (usuario_id)
);

CREATE TABLE tb_item_atendimento (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atendimento_id  BIGINT       NOT NULL,
    procedimento_id BIGINT       NOT NULL,
    numero_dente    INTEGER      NOT NULL,
    situacao_nova   VARCHAR(255) NOT NULL,
    observacao      TEXT,
    CONSTRAINT fk_item_atend_atendimento  FOREIGN KEY (atendimento_id)  REFERENCES tb_atendimento (id),
    CONSTRAINT fk_item_atend_procedimento FOREIGN KEY (procedimento_id) REFERENCES tb_procedimento (id)
);

CREATE TABLE tb_plano_tratamento (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id    BIGINT NOT NULL,
    dentista_id    BIGINT NOT NULL,
    atendimento_id BIGINT,
    observacoes    TEXT,
    criado_em      TIMESTAMP,
    atualizado_em  TIMESTAMP,
    CONSTRAINT fk_plano_paciente    FOREIGN KEY (paciente_id)    REFERENCES tb_paciente (usuario_id),
    CONSTRAINT fk_plano_dentista    FOREIGN KEY (dentista_id)    REFERENCES tb_dentista (usuario_id),
    CONSTRAINT fk_plano_atendimento FOREIGN KEY (atendimento_id) REFERENCES tb_atendimento (id)
);

CREATE TABLE tb_item_plano_tratamento (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plano_id                  BIGINT       NOT NULL,
    procedimento_id           BIGINT       NOT NULL,
    numero_dente              INTEGER      NOT NULL,
    prioridade                INTEGER,
    status                    VARCHAR(255) NOT NULL,
    observacao                TEXT,
    atendimento_realizacao_id BIGINT,
    CONSTRAINT fk_item_plano_plano        FOREIGN KEY (plano_id)                  REFERENCES tb_plano_tratamento (id),
    CONSTRAINT fk_item_plano_procedimento FOREIGN KEY (procedimento_id)           REFERENCES tb_procedimento (id),
    CONSTRAINT fk_item_plano_atend_real   FOREIGN KEY (atendimento_realizacao_id) REFERENCES tb_atendimento (id)
);

CREATE TABLE tb_odontograma_snapshot (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id    BIGINT    NOT NULL,
    atendimento_id BIGINT,
    editado_por_id BIGINT    NOT NULL,
    criado_em      TIMESTAMP NOT NULL,
    CONSTRAINT fk_snapshot_paciente    FOREIGN KEY (paciente_id)    REFERENCES tb_paciente (usuario_id),
    CONSTRAINT fk_snapshot_atendimento FOREIGN KEY (atendimento_id) REFERENCES tb_atendimento (id),
    CONSTRAINT fk_snapshot_editor      FOREIGN KEY (editado_por_id) REFERENCES tb_usuario (id)
);

CREATE TABLE tb_odontograma_dente (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id  BIGINT       NOT NULL,
    numero_dente INTEGER      NOT NULL,
    situacao     VARCHAR(255) NOT NULL,
    observacao   TEXT,
    CONSTRAINT fk_dente_snapshot FOREIGN KEY (snapshot_id) REFERENCES tb_odontograma_snapshot (id)
);

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(255)             NOT NULL,
    usuario_id BIGINT                   NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revogado   BOOLEAN                  NOT NULL,
    CONSTRAINT uk_refresh_token UNIQUE (token),
    CONSTRAINT fk_refresh_usuario FOREIGN KEY (usuario_id) REFERENCES tb_usuario (id)
);

CREATE INDEX idx_agendamento_data_inicio ON tb_agendamento (data_inicio);
CREATE INDEX idx_agendamento_paciente    ON tb_agendamento (paciente_id);
CREATE INDEX idx_agendamento_dentista    ON tb_agendamento (dentista_id);
CREATE INDEX idx_item_atend_atendimento  ON tb_item_atendimento (atendimento_id);
CREATE INDEX idx_snapshot_paciente       ON tb_odontograma_snapshot (paciente_id);
CREATE INDEX idx_dente_snapshot          ON tb_odontograma_dente (snapshot_id);
