-- Observações do paciente: entradas cronológicas (lista), distinto da anamnese (tb_paciente.observacoes_medicas).

CREATE TABLE tb_paciente_observacao (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id       BIGINT       NOT NULL,
    texto             TEXT         NOT NULL,
    autor_usuario_id  BIGINT       NOT NULL,
    criado_em         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_paciente_obs_paciente FOREIGN KEY (paciente_id) REFERENCES tb_paciente (usuario_id),
    CONSTRAINT fk_paciente_obs_autor   FOREIGN KEY (autor_usuario_id) REFERENCES tb_usuario (id)
);

CREATE INDEX idx_paciente_obs_paciente_criado ON tb_paciente_observacao (paciente_id, criado_em DESC);
