CREATE TABLE password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64)              NOT NULL,
    usuario_id BIGINT                   NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    usado      BOOLEAN                  NOT NULL,
    criado_em  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_password_reset_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_reset_usuario FOREIGN KEY (usuario_id) REFERENCES tb_usuario (id)
);

CREATE INDEX idx_password_reset_usuario ON password_reset_tokens (usuario_id);
