spring.jpa.open-in-view=false
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=20

jwt.secret=${JWT_SECRET:braFuSmLxj7ZxDzvlDDEO7xSLwSCpEzo2ofobhnCjNY=}
jwt.expiration=1800000
jwt.refresh-expiration=604800000

cors.allowed-origins=${CORS_ORIGINS:http://localhost:5173,http://localhost:3000,http://localhost:4200}